name: q35-machine

machine:
  memory: 4G
  vcpu: 4
  bios: ../share/bios-256k.bin

objects:
  - class: system-root
  - class: dummy-device
  - class: debug-console
  - class: firmware-config
  - class: pci-host

  - class: ich9-lpc
  - class: cmos
  - class: ps2

  - class: ahci-host

  - class: ich9-hda
  - class: hda-duplex
